//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test30.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PayBridge
    {
        public int PaybridgeID { get; set; }
        [Display(Name = "Invoice ID #")]

        public int InvoiceID { get; set; }

        public int PaymentID { get; set; }
        [Display(Name = "User")]

        public int UserID { get; set; }
        [Column(TypeName = "money")]
        [Display(Name = "Payment")]

            public decimal Payment { get; set; }
        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [Display(Name = "Payment Date")]
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Payment Payment1 { get; set; }
        public virtual User User { get; set; }
    }
}
