//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test30.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test30Entities : DbContext
    {
        public Test30Entities()
            : base("name=Test30Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ConnectForm> ConnectForms { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PayBridge> PayBridges { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Spoilage> Spoilages { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<UsedItem> UsedItems { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
